package com.github.its_felix.superhuman_docs_sdk.smithy.codegen;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.shapes.CollectionShape;
import software.amazon.smithy.model.shapes.EnumShape;
import software.amazon.smithy.model.shapes.MapShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ResourceShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.traits.EnumValueTrait;
import software.amazon.smithy.model.traits.HttpLabelTrait;
import software.amazon.smithy.model.traits.HttpPayloadTrait;
import software.amazon.smithy.model.traits.HttpQueryTrait;
import software.amazon.smithy.model.traits.HttpTrait;
import software.amazon.smithy.model.traits.JsonNameTrait;

final class GoRenderer {
    private static final Pattern PATH_LABEL = Pattern.compile("\\{([A-Za-z_][A-Za-z0-9_]*)}");
    private static final String GO_PACKAGE = "superhumandocs";
    private static final Set<String> GO_KEYWORDS = Set.of(
            "type", "map", "func", "var", "const", "range", "select", "case", "defer", "go", "chan",
            "interface", "struct", "package", "default", "fallthrough", "for", "if", "else", "switch",
            "return", "break", "continue");
    private static final Set<String> GO_INITIALISMS = Set.of("id", "url", "api", "acl", "oauth", "json", "http");

    private GoRenderer() {}

    static String renderTypes(Model model, String namespace) {
        List<String> lines = new ArrayList<>(List.of(
                "// Code generated by smithy/generator; DO NOT EDIT.",
                "",
                "package " + GO_PACKAGE,
                ""));
        List<Shape> shapes = SdkCodegen.dataShapesInNamespace(model, namespace);

        for (Shape shape : shapes) {
            String goName = goExportName(shape.getId().getName());
            if (isSimpleAlias(shape)) {
                lines.add("type " + goName + " " + goTargetType(preludeEquivalent(shape), model, true));
                lines.add("");
            } else if (shape.isEnumShape()) {
                EnumShape enumShape = shape.asEnumShape().orElseThrow();
                lines.add("type " + goName + " string");
                lines.add("");
                List<MemberShape> members = new ArrayList<>(enumShape.getAllMembers().values());
                if (!members.isEmpty()) {
                    lines.add("const (");
                    Set<String> used = new HashSet<>();
                    List<GoConst> constants = new ArrayList<>();
                    for (MemberShape member : members) {
                        String literal = enumLiteral(member);
                        String constant = goEnumConst(shape.getId().getName(), member.getMemberName(), literal);
                        String base = constant;
                        int n = 2;
                        while (!used.add(constant)) {
                            constant = base + n++;
                        }
                        constants.add(new GoConst(constant, goName, literal));
                    }
                    int maxName = constants.stream().mapToInt(value -> value.name().length()).max().orElse(0);
                    for (GoConst constant : constants) {
                        lines.add("\t" + padRight(constant.name(), maxName) + " " + constant.type()
                                + " = \"" + escapeGoString(constant.literal()) + "\"");
                    }
                    lines.add(")");
                    lines.add("");
                }
                lines.add("func (v " + goName + ") String() string { return string(v) }");
                lines.add("");
            } else if (shape.isListShape()) {
                CollectionShape collection = shape.asListShape().orElseThrow();
                lines.add("type " + goName + " []" + goTargetType(collection.getMember().getTarget(), model, true));
                lines.add("");
            } else if (shape.isMapShape()) {
                MapShape map = shape.asMapShape().orElseThrow();
                lines.add("type " + goName + " map[" + goTargetType(map.getKey().getTarget(), model, true)
                        + "]" + goTargetType(map.getValue().getTarget(), model, true));
                lines.add("");
            } else if (shape.isStructureShape() || shape.isUnionShape()) {
                lines.add("type " + goName + " struct {");
                Set<String> usedFields = new HashSet<>();
                List<GoField> fields = new ArrayList<>();
                for (MemberShape member : shape.members()) {
                    String field = goFieldName(member.getMemberName());
                    String base = field;
                    int n = 2;
                    while (!usedFields.add(field)) {
                        field = base + n++;
                    }
                    boolean required = member.isRequired() && shape.isStructureShape();
                    String tag = jsonName(member);
                    if (!required) {
                        tag += ",omitempty";
                    }
                    fields.add(new GoField(field, goTargetType(member.getTarget(), model, required), tag));
                }
                int maxField = fields.stream().mapToInt(value -> value.name().length()).max().orElse(0);
                int maxType = fields.stream().mapToInt(value -> value.type().length()).max().orElse(0);
                for (GoField field : fields) {
                    lines.add("\t" + padRight(field.name(), maxField) + " " + padRight(field.type(), maxType)
                            + " `json:\"" + field.jsonTag() + "\"`");
                }
                lines.add("}");
                lines.add("");
            }
        }
        return String.join("\n", trimTrailingBlank(lines)) + "\n";
    }

    static String renderOperations(Model model, ServiceShape service) {
        List<SdkCodegen.OperationBinding> bindings = SdkCodegen.operationBindings(model, service);
        List<ResourceShape> resources = SdkCodegen.resourcesInServiceOrder(model, service);
        List<ResourceShape> topLevelResources = SdkCodegen.topLevelResourcesInServiceOrder(model, service);
        List<String> lines = new ArrayList<>(List.of(
                "// Code generated by smithy/generator; DO NOT EDIT.",
                "",
                "package " + GO_PACKAGE,
                "",
                "import (",
                "\t\"context\"",
                "\t\"net/http\"",
                "\t\"net/url\"",
                ")",
                ""));

        for (ResourceShape resource : resources) {
            String clientType = goExportName(SdkCodegen.resourceAccessorName(resource)) + "ResourceClient";
            lines.add("type " + clientType + " struct {");
            lines.add("\tclient *Client");
            lines.add("}");
            lines.add("");
        }
        for (ResourceShape resource : topLevelResources) {
            String clientType = goExportName(SdkCodegen.resourceAccessorName(resource)) + "ResourceClient";
            String accessor = goExportName(SdkCodegen.resourceAccessorName(resource));
            lines.add("func (c *Client) " + accessor + "() *" + clientType + " {");
            lines.add("\treturn &" + clientType + "{client: c}");
            lines.add("}");
            lines.add("");
        }

        Map<ShapeId, ResourceShape> parents = SdkCodegen.resourceParents(model, service);
        for (ResourceShape resource : resources) {
            ResourceShape parent = parents.get(resource.getId());
            if (parent == null) {
                continue;
            }
            String parentType = goExportName(SdkCodegen.resourceAccessorName(parent)) + "ResourceClient";
            String childType = goExportName(SdkCodegen.resourceAccessorName(resource)) + "ResourceClient";
            String accessor = goExportName(SdkCodegen.resourceAccessorName(resource));
            lines.add("func (r *" + parentType + ") " + accessor + "() *" + childType + " {");
            lines.add("\treturn &" + childType + "{client: r.client}");
            lines.add("}");
            lines.add("");
        }

        for (SdkCodegen.OperationBinding binding : bindings) {
            OperationShape operation = binding.operation();
            String outputType = operation.getOutput().map(id -> "*" + goExportName(id.getName())).orElse("any");
            String receiver;
            String clientExpression;
            if (binding.isServiceOperation()) {
                receiver = "c *Client";
                clientExpression = "c";
            } else {
                String clientType = goExportName(SdkCodegen.resourceAccessorName(binding.resource())) + "ResourceClient";
                receiver = "r *" + clientType;
                clientExpression = "r.client";
            }
            String methodName = goExportName(binding.methodName());
            if (operation.getInput().isPresent()) {
                String inputType = "*" + goExportName(operation.getInput().orElseThrow().getName());
                lines.add("func (" + receiver + ") " + methodName
                        + "(ctx context.Context, input " + inputType + ") (" + outputType + ", error) {");
                lines.add("\tif input == nil {");
                lines.add("\t\tinput = &" + goExportName(operation.getInput().orElseThrow().getName()) + "{}");
                lines.add("\t}");
            } else {
                lines.add("func (" + receiver + ") " + methodName
                        + "(ctx context.Context) (" + outputType + ", error) {");
            }
            lines.add("\tpath := " + goPath(operation, model));
            lines.add("\tquery := url.Values{}");
            String payload = "nil";
            for (MemberShape member : inputMembers(model, operation)) {
                String field = goFieldName(member.getMemberName());
                if (member.hasTrait(HttpQueryTrait.class)) {
                    lines.add("\taddQueryValue(query, \"" + escapeGoString(member.expectTrait(HttpQueryTrait.class).getValue())
                            + "\", input." + field + ")");
                } else if (member.hasTrait(HttpPayloadTrait.class)) {
                    payload = "input." + field;
                }
            }
            HttpTrait http = operation.expectTrait(HttpTrait.class);
            if (outputType.equals("any")) {
                lines.add("\terr := " + clientExpression + ".do(ctx, http.Method" + goMethodConst(http.getMethod()) + ", path, query, " + payload + ", nil)");
                lines.add("\treturn nil, err");
            } else {
                String out = goExportName(operation.getOutput().orElseThrow().getName());
                lines.add("\tvar out " + out);
                lines.add("\terr := " + clientExpression + ".do(ctx, http.Method" + goMethodConst(http.getMethod()) + ", path, query, " + payload + ", &out)");
                lines.add("\treturn &out, err");
            }
            lines.add("}");
            lines.add("");
        }
        return String.join("\n", trimTrailingBlank(lines)) + "\n";
    }

    private static List<MemberShape> inputMembers(Model model, OperationShape operation) {
        return operation.getInput()
                .map(id -> new ArrayList<>(model.expectShape(id).members()))
                .orElseGet(ArrayList::new);
    }

    private static boolean isSimpleAlias(Shape shape) {
        return switch (shape.getType()) {
            case STRING, INTEGER, LONG, DOUBLE, BOOLEAN, BLOB, TIMESTAMP, DOCUMENT -> true;
            default -> false;
        };
    }

    private static ShapeId preludeEquivalent(Shape shape) {
        return switch (shape.getType()) {
            case STRING -> ShapeId.from("smithy.api#String");
            case INTEGER -> ShapeId.from("smithy.api#Integer");
            case LONG -> ShapeId.from("smithy.api#Long");
            case DOUBLE -> ShapeId.from("smithy.api#Double");
            case BOOLEAN -> ShapeId.from("smithy.api#Boolean");
            case BLOB -> ShapeId.from("smithy.api#Blob");
            case TIMESTAMP -> ShapeId.from("smithy.api#Timestamp");
            case DOCUMENT -> ShapeId.from("smithy.api#Document");
            default -> shape.getId();
        };
    }

    private static String goTargetType(ShapeId target, Model model, boolean required) {
        String type;
        if (target.getNamespace().equals("smithy.api")) {
            type = switch (target.getName()) {
                case "String" -> "string";
                case "Integer" -> "int";
                case "Long" -> "int64";
                case "Double", "Float" -> "float64";
                case "Boolean" -> "bool";
                case "Blob" -> "[]byte";
                case "Document" -> "any";
                case "Timestamp" -> "string";
                default -> goExportName(target.getName());
            };
        } else {
            Shape shape = model.expectShape(target);
            if (shape.isListShape()) {
                type = "[]" + goTargetType(shape.asListShape().orElseThrow().getMember().getTarget(), model, true);
            } else if (shape.isMapShape()) {
                MapShape map = shape.asMapShape().orElseThrow();
                type = "map[" + goTargetType(map.getKey().getTarget(), model, true) + "]"
                        + goTargetType(map.getValue().getTarget(), model, true);
            } else {
                type = goExportName(target.getName());
            }
        }
        if (required || type.startsWith("[]") || type.startsWith("map[") || type.equals("any") || type.equals("[]byte")) {
            return type;
        }
        return "*" + type;
    }

    private static String goExportName(String name) {
        Matcher matcher = Pattern.compile("[A-Za-z]+|[0-9]+").matcher(name.replace("_", " "));
        List<String> parts = new ArrayList<>();
        while (matcher.find()) {
            parts.add(matcher.group());
        }
        if (parts.isEmpty()) {
            return "Value";
        }
        StringBuilder result = new StringBuilder();
        for (String part : parts) {
            String lower = part.toLowerCase(Locale.ROOT);
            if (GO_INITIALISMS.contains(lower)) {
                result.append(switch (lower) {
                    case "id" -> "ID";
                    case "url" -> "URL";
                    case "api" -> "API";
                    case "acl" -> "ACL";
                    case "oauth" -> "OAuth";
                    case "json" -> "JSON";
                    case "http" -> "HTTP";
                    default -> part;
                });
            } else {
                result.append(part.substring(0, 1).toUpperCase(Locale.ROOT)).append(part.substring(1));
            }
        }
        String value = result.toString();
        if (Set.of("Type", "Map", "Func", "Var").contains(value)) {
            value += "Value";
        }
        if (!value.isEmpty() && Character.isDigit(value.charAt(0))) {
            value = "Value" + value;
        }
        return value;
    }

    private static String goFieldName(String name) {
        String field = goExportName(name);
        return GO_KEYWORDS.contains(field.toLowerCase(Locale.ROOT)) ? field + "Value" : field;
    }

    private static String goEnumConst(String shapeName, String memberName, String literal) {
        // Smithy models commonly use SCREAMING_SNAKE_CASE member names while
        // Go exported constants conventionally use PascalCase. Prefer the wire
        // value because it also preserves meaningful word boundaries in values
        // such as `dateTime`; fall back to the Smithy member name for symbolic
        // values that do not contain identifier characters.
        String identifierSource = literal;
        if (!literal.isEmpty() && literal.equals(literal.toUpperCase(Locale.ROOT))) {
            identifierSource = literal.toLowerCase(Locale.ROOT);
        }
        String suffix = identifierSource.isEmpty() ? "Value" : goExportName(identifierSource);
        if (suffix.equals("Value")) {
            suffix = goExportName(memberName);
        }
        return goExportName(shapeName) + suffix;
    }

    private static String jsonName(MemberShape member) {
        return member.getTrait(JsonNameTrait.class).map(JsonNameTrait::getValue).orElse(member.getMemberName());
    }

    private static String enumLiteral(MemberShape member) {
        return member.getTrait(EnumValueTrait.class).flatMap(EnumValueTrait::getStringValue).orElse(member.getMemberName());
    }

    private static String goPath(OperationShape operation, Model model) {
        Map<String, String> labels = new LinkedHashMap<>();
        for (MemberShape member : inputMembers(model, operation)) {
            if (member.hasTrait(HttpLabelTrait.class)) {
                labels.put(member.getMemberName(), goFieldName(member.getMemberName()));
            }
        }
        List<String> parts = new ArrayList<>();
        String uri = operation.expectTrait(HttpTrait.class).getUri().toString();
        int pos = 0;
        Matcher matcher = PATH_LABEL.matcher(uri);
        while (matcher.find()) {
            if (matcher.start() > pos) {
                parts.add("\"" + escapeGoString(uri.substring(pos, matcher.start())) + "\"");
            }
            String field = labels.get(matcher.group(1));
            if (field == null) {
                throw new IllegalStateException("Missing @httpLabel member " + matcher.group(1)
                        + " for " + operation.getId());
            }
            parts.add("pathEscape(input." + field + ")");
            pos = matcher.end();
        }
        if (pos < uri.length()) {
            parts.add("\"" + escapeGoString(uri.substring(pos)) + "\"");
        }
        return parts.isEmpty() ? "\"\"" : String.join(" + ", parts);
    }

    private static String escapeGoString(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static String goMethodConst(String method) {
        return switch (method.toUpperCase(Locale.ROOT)) {
            case "GET" -> "Get";
            case "POST" -> "Post";
            case "PUT" -> "Put";
            case "PATCH" -> "Patch";
            case "DELETE" -> "Delete";
            case "HEAD" -> "Head";
            default -> "Get";
        };
    }

    private static List<String> trimTrailingBlank(List<String> lines) {
        while (!lines.isEmpty() && lines.get(lines.size() - 1).isEmpty()) {
            lines.remove(lines.size() - 1);
        }
        return lines;
    }

    private static String padRight(String value, int width) {
        if (value.length() >= width) {
            return value;
        }
        return value + " ".repeat(width - value.length());
    }

    private record GoConst(String name, String type, String literal) {}

    private record GoField(String name, String type, String jsonTag) {}
}
