package com.github.its_felix.superhuman_docs_sdk.smithy.codegen;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.shapes.CollectionShape;
import software.amazon.smithy.model.shapes.EnumShape;
import software.amazon.smithy.model.shapes.MapShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.traits.EnumValueTrait;
import software.amazon.smithy.model.traits.JsonNameTrait;

final class PythonModelRenderer {
    private static final Set<String> KEYWORDS = Set.of(
            "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class",
            "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global",
            "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return",
            "try", "while", "with", "yield");

    private PythonModelRenderer() {}

    static String render(Model model, String namespace) {
        List<Shape> shapes = SdkCodegen.dataShapesInNamespace(model, namespace);
        List<String> lines = new ArrayList<>(List.of(
                "# Code generated by smithy/generator; DO NOT EDIT.",
                "from __future__ import annotations",
                "",
                "from dataclasses import dataclass, field",
                "from enum import Enum",
                "from typing import Any, NewType, TypeAlias",
                ""));

        for (Shape shape : shapes) {
            if (isSimpleAlias(shape)) {
                lines.add(shape.getId().getName() + " = NewType(\"" + shape.getId().getName() + "\", "
                        + pythonPreludeType(shape) + ")");
                lines.add("");
            } else if (shape.isEnumShape()) {
                renderEnum(lines, shape.asEnumShape().orElseThrow());
            }
        }
        for (Shape shape : shapes) {
            if (shape.isStructureShape() || shape.isUnionShape()) {
                renderAggregate(lines, model, shape);
            }
        }
        for (Shape shape : shapes) {
            if (shape.isListShape()) {
                CollectionShape list = shape.asListShape().orElseThrow();
                lines.add(shape.getId().getName() + ": TypeAlias = list["
                        + pythonType(model, list.getMember().getTarget()) + "]");
                lines.add("");
            } else if (shape.isMapShape()) {
                MapShape map = shape.asMapShape().orElseThrow();
                lines.add(shape.getId().getName() + ": TypeAlias = dict["
                        + pythonType(model, map.getKey().getTarget()) + ", "
                        + pythonType(model, map.getValue().getTarget()) + "]");
                lines.add("");
            }
        }
        lines.add("__all__ = (");
        for (Shape shape : shapes) {
            lines.add("    \"" + shape.getId().getName() + "\",");
        }
        lines.add(")");
        while (!lines.isEmpty() && lines.get(lines.size() - 1).isEmpty()) lines.remove(lines.size() - 1);
        return String.join("\n", lines) + "\n";
    }

    private static void renderEnum(List<String> lines, EnumShape shape) {
        lines.add("class " + shape.getId().getName() + "(str, Enum):");
        List<MemberShape> members = new ArrayList<>(shape.getAllMembers().values());
        if (members.isEmpty()) {
            lines.add("    pass");
        } else {
            for (MemberShape member : members) {
                String value = member.getTrait(EnumValueTrait.class)
                        .flatMap(EnumValueTrait::getStringValue)
                        .orElse(member.getMemberName());
                lines.add("    " + enumName(member.getMemberName()) + " = " + repr(value));
            }
        }
        lines.add("");
    }

    private static void renderAggregate(List<String> lines, Model model, Shape shape) {
        lines.add("@dataclass(kw_only=True)");
        lines.add("class " + shape.getId().getName() + ":");
        List<MemberShape> members = new ArrayList<>(shape.members());
        members.sort(Comparator.comparing(member -> member.isRequired() ? 0 : 1));
        if (members.isEmpty()) {
            lines.add("    pass");
            lines.add("");
            return;
        }
        for (MemberShape member : members) {
            boolean required = member.isRequired() && shape.isStructureShape();
            String type = pythonType(model, member.getTarget());
            String jsonName = member.getTrait(JsonNameTrait.class).map(JsonNameTrait::getValue)
                    .orElse(member.getMemberName());
            String suffix = required ? "" : " | None";
            lines.add("    " + safeName(toSnake(member.getMemberName())) + ": " + type + suffix
                    + " = field("
                    + (required ? "" : "default=None, ") + "metadata={\"json_name\": " + repr(jsonName) + "})");
        }
        if (shape.isUnionShape()) {
            lines.add("");
            lines.add("    def __post_init__(self) -> None:");
            String values = String.join(", ", members.stream()
                    .map(member -> "self." + safeName(toSnake(member.getMemberName())))
                    .toList());
            lines.add("        if sum(value is not None for value in (" + values
                    + (members.size() == 1 ? "," : "") + ")) != 1:");
            lines.add("            raise ValueError(\"Exactly one union member must be set\")");
        }
        lines.add("");
    }

    private static String pythonType(Model model, ShapeId target) {
        if (target.getNamespace().equals("smithy.api")) {
            return switch (target.getName()) {
                case "String", "Timestamp" -> "str";
                case "Byte", "Short", "Integer", "Long", "BigInteger" -> "int";
                case "Float", "Double", "BigDecimal" -> "float";
                case "Boolean" -> "bool";
                case "Blob" -> "bytes";
                case "Document" -> "Any";
                default -> "Any";
            };
        }
        return model.expectShape(target).getId().getName();
    }

    private static boolean isSimpleAlias(Shape shape) {
        return switch (shape.getType()) {
            case STRING, BYTE, SHORT, INTEGER, LONG, BIG_INTEGER, FLOAT, DOUBLE, BIG_DECIMAL,
                    BOOLEAN, BLOB, TIMESTAMP, DOCUMENT -> true;
            default -> false;
        };
    }

    private static String pythonPreludeType(Shape shape) {
        return switch (shape.getType()) {
            case STRING, TIMESTAMP -> "str";
            case BYTE, SHORT, INTEGER, LONG, BIG_INTEGER -> "int";
            case FLOAT, DOUBLE, BIG_DECIMAL -> "float";
            case BOOLEAN -> "bool";
            case BLOB -> "bytes";
            default -> "Any";
        };
    }

    private static String enumName(String value) {
        String name = value.replaceAll("[^A-Za-z0-9_]", "_").toUpperCase(Locale.ROOT);
        if (name.isEmpty()) name = "VALUE";
        if (Character.isDigit(name.charAt(0))) name = "VALUE_" + name;
        return name;
    }

    private static String toSnake(String value) {
        String first = value.replaceAll("(.)([A-Z][a-z]+)", "$1_$2");
        return first.replaceAll("([a-z0-9])([A-Z])", "$1_$2").toLowerCase(Locale.ROOT);
    }

    private static String safeName(String value) {
        return KEYWORDS.contains(value) ? value + "_" : value;
    }

    private static String repr(String value) {
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'";
    }
}
