package com.github.its_felix.superhuman_docs_sdk.smithy.codegen;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ResourceShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.traits.DocumentationTrait;
import software.amazon.smithy.model.traits.HttpLabelTrait;
import software.amazon.smithy.model.traits.HttpPayloadTrait;
import software.amazon.smithy.model.traits.HttpQueryTrait;
import software.amazon.smithy.model.traits.HttpTrait;

final class PythonRenderer {
    private static final Pattern PATH_LABEL = Pattern.compile("\\{([A-Za-z_][A-Za-z0-9_]*)}");
    private static final Set<String> PYTHON_KEYWORDS = Set.of(
            "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
            "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in",
            "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with", "yield");

    private PythonRenderer() {}

    static String render(Model model, ServiceShape service) {
        List<SdkCodegen.OperationBinding> bindings = SdkCodegen.operationBindings(model, service);
        List<ResourceShape> resources = SdkCodegen.resourcesInServiceOrder(model, service);
        List<ResourceShape> topLevelResources = SdkCodegen.topLevelResourcesInServiceOrder(model, service);
        List<String> lines = new ArrayList<>(List.of(
                "# Code generated by smithy/generator; DO NOT EDIT.",
                "from __future__ import annotations",
                "",
                "from typing import Any",
                "",
                "from ._models import *  # noqa: F403",
                "from ._runtime import Operation, PathLabel, QueryBinding",
                "",
                "",
                "OPERATIONS = {"));

        for (SdkCodegen.OperationBinding binding : bindings) {
            OperationShape operation = binding.operation();
            HttpTrait http = operation.expectTrait(HttpTrait.class);
            List<MemberShape> members = inputMembers(model, operation);
            List<String> labels = members.stream().filter(member -> member.hasTrait(HttpLabelTrait.class))
                    .map(MemberShape::getMemberName).toList();
            List<MemberShape> queries = members.stream().filter(member -> member.hasTrait(HttpQueryTrait.class)).toList();
            String payload = members.stream().filter(member -> member.hasTrait(HttpPayloadTrait.class))
                    .map(MemberShape::getMemberName).findFirst().orElse(null);
            List<String> required = members.stream().filter(MemberShape::isRequired).map(MemberShape::getMemberName).toList();

            lines.add("    \"" + operation.getId().getName() + "\": Operation(");
            lines.add("        name=\"" + operation.getId().getName() + "\",");
            lines.add("        method=\"" + http.getMethod() + "\",");
            lines.add("        path=\"" + http.getUri() + "\",");
            lines.add("        status_code=" + http.getCode() + ",");
            lines.add("        path_parts=" + pythonPathParts(http.getUri().toString()) + ",");
            lines.add("        labels=" + pythonTuple(labels, true) + ",");
            lines.add("        queries=" + pythonQueries(queries) + ",");
            lines.add("        payload=" + pythonOptionalString(payload) + ",");
            lines.add("        required=" + pythonTuple(required, true) + ",");
            lines.add("    ),");
        }
        lines.add("}");
        lines.add("");

        Map<ShapeId, ResourceShape> parents = SdkCodegen.resourceParents(model, service);
        for (ResourceShape resource : resources) {
            String className = resourceClass(resource);
            lines.add("");
            lines.add("class " + className + ":");
            lines.add("    def __init__(self, client: Any) -> None:");
            lines.add("        self._client = client");
            boolean emitted = false;
            for (ResourceShape child : resources) {
                if (resource.equals(parents.get(child.getId()))) {
                    emitted = true;
                    lines.add("");
                    lines.add("    def " + toSnake(SdkCodegen.resourceAccessorName(child)) + "(self) -> "
                            + resourceClass(child) + ":");
                    lines.add("        return " + resourceClass(child) + "(self._client)");
                }
            }
            for (SdkCodegen.OperationBinding binding : bindings) {
                if (resource.equals(binding.resource())) {
                    emitted = true;
                    lines.add("");
                    lines.addAll(renderMethod(model, binding, "    ", "self._client"));
                }
            }
            if (!emitted) lines.add("    pass");
        }

        lines.add("");
        lines.add("");
        lines.add("class GeneratedServiceClientMixin:");
        boolean serviceMethod = false;
        for (SdkCodegen.OperationBinding binding : bindings) {
            if (binding.isServiceOperation()) {
                serviceMethod = true;
                lines.add("");
                lines.addAll(renderMethod(model, binding, "    ", "self"));
            }
        }
        for (ResourceShape resource : topLevelResources) {
            serviceMethod = true;
            lines.add("");
            lines.add("    def " + toSnake(SdkCodegen.resourceAccessorName(resource)) + "(self) -> "
                    + resourceClass(resource) + ":");
            lines.add("        return " + resourceClass(resource) + "(self)");
        }
        if (!serviceMethod) lines.add("    pass");
        return String.join("\n", trimTrailingBlank(lines)) + "\n";
    }

    private static List<String> renderMethod(
            Model model,
            SdkCodegen.OperationBinding binding,
            String indent,
            String clientExpression
    ) {
        OperationShape operation = binding.operation();
        List<MemberShape> members = inputMembers(model, operation);
        boolean hasRequired = members.stream().anyMatch(MemberShape::isRequired);
        String inputType = operation.getInput().map(ShapeId::getName).orElse("None");
        String outputType = operation.getOutput().map(ShapeId::getName).orElse("None");
        String signature;
        if (operation.getInput().isEmpty()) {
            signature = "self";
        } else if (hasRequired) {
            signature = "self, options: " + inputType;
        } else {
            signature = "self, options: " + inputType + " | None = None";
        }

        HttpTrait http = operation.expectTrait(HttpTrait.class);
        String doc = operation.getTrait(DocumentationTrait.class).map(DocumentationTrait::getValue)
                .orElse(operation.getId().getName());
        List<String> lines = new ArrayList<>();
        lines.add(indent + "def " + toSnake(binding.methodName()) + "(" + signature + ") -> " + outputType + ":");
        lines.add(indent + "    \"\"\"" + escapePythonDoc(doc));
        lines.add("");
        lines.add(indent + "    HTTP " + http.getMethod() + " " + http.getUri());
        lines.add(indent + "    \"\"\"");
        if (operation.getInput().isPresent() && !hasRequired) {
            lines.add(indent + "    if options is None:");
            lines.add(indent + "        options = " + inputType + "()");
        }
        if (members.isEmpty()) {
            lines.add(indent + "    params = {}");
        } else {
            lines.add(indent + "    params = {");
            for (MemberShape member : members) {
                lines.add(indent + "        \"" + member.getMemberName() + "\": options."
                        + pythonSafeName(toSnake(member.getMemberName())) + ",");
            }
            lines.add(indent + "    }");
        }
        lines.add(indent + "    return " + clientExpression + "._request(OPERATIONS[\""
                + operation.getId().getName() + "\"], params, " + outputType + ")");
        return lines;
    }

    private static String resourceClass(ResourceShape resource) {
        return SdkCodegen.resourceAccessorName(resource) + "ResourceClient";
    }

    private static List<MemberShape> inputMembers(Model model, OperationShape operation) {
        return operation.getInput().map(id -> new ArrayList<>(model.expectShape(id).members()))
                .orElseGet(ArrayList::new);
    }

    private static String pythonQueries(List<MemberShape> queries) {
        if (queries.isEmpty()) return "()";
        List<String> values = new ArrayList<>();
        for (MemberShape member : queries) {
            values.add("QueryBinding(\"" + member.getMemberName() + "\", \""
                    + member.expectTrait(HttpQueryTrait.class).getValue() + "\")");
        }
        return "(" + String.join(", ", values) + (values.size() == 1 ? "," : "") + ")";
    }

    private static String pythonPathParts(String path) {
        List<String> parts = new ArrayList<>();
        int pos = 0;
        Matcher matcher = PATH_LABEL.matcher(path);
        while (matcher.find()) {
            if (matcher.start() > pos) parts.add(pythonRepr(path.substring(pos, matcher.start())));
            parts.add("PathLabel(\"" + matcher.group(1) + "\")");
            pos = matcher.end();
        }
        if (pos < path.length()) parts.add(pythonRepr(path.substring(pos)));
        return tupleExpression(parts);
    }

    private static String pythonTuple(List<String> values, boolean quote) {
        return tupleExpression(quote ? values.stream().map(PythonRenderer::pythonRepr).toList() : values);
    }

    private static String tupleExpression(List<String> items) {
        if (items.isEmpty()) return "()";
        return "(" + String.join(", ", items) + (items.size() == 1 ? "," : "") + ")";
    }

    private static String pythonOptionalString(String value) {
        return value == null ? "None" : pythonRepr(value);
    }

    private static String pythonRepr(String value) {
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'";
    }

    private static String toSnake(String value) {
        String first = value.replaceAll("(.)([A-Z][a-z]+)", "$1_$2");
        return first.replaceAll("([a-z0-9])([A-Z])", "$1_$2").toLowerCase(Locale.ROOT);
    }

    private static String pythonSafeName(String value) {
        return PYTHON_KEYWORDS.contains(value) ? value + "_" : value;
    }

    private static String escapePythonDoc(String value) {
        return value.replace("\\", "\\\\").replace("\"\"\"", "\\\"\\\"\\\"");
    }

    private static List<String> trimTrailingBlank(List<String> lines) {
        while (!lines.isEmpty() && lines.get(lines.size() - 1).isEmpty()) lines.remove(lines.size() - 1);
        return lines;
    }
}
