package com.github.its_felix.superhuman_docs_sdk.smithy.codegen;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.traits.DocumentationTrait;
import software.amazon.smithy.model.traits.HttpLabelTrait;
import software.amazon.smithy.model.traits.HttpPayloadTrait;
import software.amazon.smithy.model.traits.HttpQueryTrait;
import software.amazon.smithy.model.traits.HttpTrait;

final class PythonRenderer {
    private static final Pattern PATH_LABEL = Pattern.compile("\\{([A-Za-z_][A-Za-z0-9_]*)}");
    private static final Set<String> PYTHON_KEYWORDS = Set.of(
            "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
            "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in",
            "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with", "yield");

    private PythonRenderer() {}

    static String render(Model model, List<OperationShape> operations) {
        List<String> lines = new ArrayList<>(List.of(
                "# Code generated by smithy/generator; DO NOT EDIT.",
                "from __future__ import annotations",
                "",
                "from typing import Any",
                "",
                "from ._runtime import Operation, PathLabel, QueryBinding",
                "",
                "",
                "OPERATIONS = {"));

        for (OperationShape operation : operations) {
            HttpTrait http = operation.expectTrait(HttpTrait.class);
            List<MemberShape> members = inputMembers(model, operation);
            List<String> labels = members.stream().filter(member -> member.hasTrait(HttpLabelTrait.class))
                    .map(MemberShape::getMemberName).toList();
            List<MemberShape> queries = members.stream().filter(member -> member.hasTrait(HttpQueryTrait.class)).toList();
            String payload = members.stream().filter(member -> member.hasTrait(HttpPayloadTrait.class))
                    .map(MemberShape::getMemberName).findFirst().orElse(null);
            List<String> required = members.stream().filter(MemberShape::isRequired).map(MemberShape::getMemberName).toList();

            lines.add("    \"" + operation.getId().getName() + "\": Operation(");
            lines.add("        name=\"" + operation.getId().getName() + "\",");
            lines.add("        method=\"" + http.getMethod() + "\",");
            lines.add("        path=\"" + http.getUri() + "\",");
            lines.add("        status_code=" + http.getCode() + ",");
            lines.add("        path_parts=" + pythonPathParts(http.getUri().toString()) + ",");
            lines.add("        labels=" + pythonTuple(labels, true) + ",");
            lines.add("        queries=" + pythonQueries(queries) + ",");
            lines.add("        payload=" + pythonOptionalString(payload) + ",");
            lines.add("        required=" + pythonTuple(required, true) + ",");
            lines.add("    ),");
        }

        lines.add("}");
        lines.add("");
        lines.add("");
        lines.add("class GeneratedOperationsMixin:");
        lines.add("");
        for (OperationShape operation : operations) {
            lines.addAll(renderMethod(model, operation));
            lines.add("");
        }
        return String.join("\n", trimTrailingBlank(lines)) + "\n";
    }

    private static List<String> renderMethod(Model model, OperationShape operation) {
        List<MemberShape> members = inputMembers(model, operation);
        List<MemberShape> requiredMembers = members.stream().filter(MemberShape::isRequired).toList();
        List<MemberShape> optionalMembers = members.stream().filter(member -> !member.isRequired()).toList();
        List<MemberShape> orderedMembers = new ArrayList<>();
        orderedMembers.addAll(requiredMembers);
        orderedMembers.addAll(optionalMembers);
        Map<String, String> paramNames = new LinkedHashMap<>();
        for (MemberShape member : orderedMembers) {
            paramNames.put(member.getMemberName(), pythonSafeName(toSnake(member.getMemberName())));
        }

        List<String> signatureParts = new ArrayList<>();
        for (MemberShape member : requiredMembers) {
            signatureParts.add(paramNames.get(member.getMemberName()) + ": Any");
        }
        for (MemberShape member : optionalMembers) {
            signatureParts.add(paramNames.get(member.getMemberName()) + ": Any = None");
        }
        String signature = signatureParts.isEmpty() ? "self" : "self, *, " + String.join(", ", signatureParts);
        HttpTrait http = operation.expectTrait(HttpTrait.class);
        String doc = operation.getTrait(DocumentationTrait.class).map(DocumentationTrait::getValue)
                .orElse(operation.getId().getName());
        List<String> lines = new ArrayList<>();
        lines.add("    def " + toSnake(operation.getId().getName()) + "(" + signature + ") -> Any:");
        lines.add("        \"\"\"" + escapePythonDoc(doc));
        lines.add("");
        lines.add("        HTTP " + http.getMethod() + " " + http.getUri());
        lines.add("        \"\"\"");
        if (orderedMembers.isEmpty()) {
            lines.add("        params = {}");
        } else {
            lines.add("        params = {");
            for (MemberShape member : orderedMembers) {
                lines.add("            \"" + member.getMemberName() + "\": " + paramNames.get(member.getMemberName()) + ",");
            }
            lines.add("        }");
        }
        lines.add("        return self._request(OPERATIONS[\"" + operation.getId().getName() + "\"], params)");
        return lines;
    }

    private static List<MemberShape> inputMembers(Model model, OperationShape operation) {
        return operation.getInput()
                .map(id -> new ArrayList<>(model.expectShape(id).members()))
                .orElseGet(ArrayList::new);
    }

    private static String pythonQueries(List<MemberShape> queries) {
        if (queries.isEmpty()) {
            return "()";
        }
        List<String> values = new ArrayList<>();
        for (MemberShape member : queries) {
            String query = member.expectTrait(HttpQueryTrait.class).getValue();
            values.add("QueryBinding(\"" + member.getMemberName() + "\", \"" + query + "\")");
        }
        return "(" + String.join(", ", values) + (values.size() == 1 ? "," : "") + ")";
    }

    private static String pythonPathParts(String path) {
        List<String> parts = new ArrayList<>();
        int pos = 0;
        Matcher matcher = PATH_LABEL.matcher(path);
        while (matcher.find()) {
            if (matcher.start() > pos) {
                parts.add(pythonRepr(path.substring(pos, matcher.start())));
            }
            parts.add("PathLabel(\"" + matcher.group(1) + "\")");
            pos = matcher.end();
        }
        if (pos < path.length()) {
            parts.add(pythonRepr(path.substring(pos)));
        }
        return tupleExpression(parts);
    }

    private static String pythonTuple(List<String> values, boolean quote) {
        List<String> items = quote ? values.stream().map(PythonRenderer::pythonRepr).toList() : values;
        return tupleExpression(items);
    }

    private static String tupleExpression(List<String> items) {
        if (items.isEmpty()) {
            return "()";
        }
        if (items.size() == 1) {
            return "(" + items.get(0) + ",)";
        }
        return "(" + String.join(", ", items) + ")";
    }

    private static String pythonOptionalString(String value) {
        return value == null ? "None" : pythonRepr(value);
    }

    private static String pythonRepr(String value) {
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'";
    }

    private static String toSnake(String value) {
        String first = value.replaceAll("(.)([A-Z][a-z]+)", "$1_$2");
        return first.replaceAll("([a-z0-9])([A-Z])", "$1_$2").toLowerCase(Locale.ROOT);
    }

    private static String pythonSafeName(String value) {
        return PYTHON_KEYWORDS.contains(value) ? value + "_" : value;
    }

    private static String escapePythonDoc(String value) {
        return value.replace("\\", "\\\\").replace("\"\"\"", "\\\"\\\"\\\"");
    }

    private static List<String> trimTrailingBlank(List<String> lines) {
        while (!lines.isEmpty() && lines.get(lines.size() - 1).isEmpty()) {
            lines.remove(lines.size() - 1);
        }
        return lines;
    }
}
