package com.github.its_felix.superhuman_docs_sdk.smithy.codegen;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.shapes.CollectionShape;
import software.amazon.smithy.model.shapes.EnumShape;
import software.amazon.smithy.model.shapes.MapShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ResourceShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.ShapeType;
import software.amazon.smithy.model.traits.EnumValueTrait;
import software.amazon.smithy.model.traits.HttpLabelTrait;
import software.amazon.smithy.model.traits.HttpPayloadTrait;
import software.amazon.smithy.model.traits.HttpQueryTrait;
import software.amazon.smithy.model.traits.HttpTrait;
import software.amazon.smithy.model.traits.JsonNameTrait;

final class RustRenderer {
    private static final Pattern PATH_LABEL = Pattern.compile("\\{([A-Za-z_][A-Za-z0-9_]*)}");
    private static final Set<String> RUST_KEYWORDS = Set.of(
            "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
            "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
            "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
            "where", "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final",
            "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try");

    private RustRenderer() {}

    static String render(
            Model model,
            String namespace,
            List<SdkCodegen.OperationBinding> bindings,
            List<ResourceShape> resources,
            List<ResourceShape> topLevelResources
    ) {
        List<String> lines = new ArrayList<>(List.of(
                "// Code generated by smithy/generator; DO NOT EDIT.",
                "",
                "use crate::core::{Client, Error, Method, Request, UrlBuilder};",
                "",
                "pub const OPERATION_COUNT: usize = " + bindings.size() + ";",
                ""));

        lines.addAll(renderModels(model, namespace));
        lines.add("");
        lines.add("pub use models::*;");
        lines.add("");

        for (SdkCodegen.OperationBinding binding : bindings) {
            lines.addAll(renderBuilder(model, binding.operation()));
            lines.add("");
        }

        lines.addAll(renderResourceClients(model, bindings, resources, topLevelResources));
        lines.add("");
        lines.add("#[cfg(test)]");
        lines.add("mod tests {");
        lines.add("    use super::*;");
        lines.add("");
        lines.add("    #[test]");
        lines.add("    fn generated_operation_count_tracks_smithy_service() {");
        lines.add("        assert_eq!(OPERATION_COUNT, " + bindings.size() + ");");
        lines.add("    }");
        lines.add("}");
        lines.add("");
        return String.join("\n", lines);
    }

    private static List<String> renderModels(Model model, String namespace) {
        List<String> lines = new ArrayList<>(List.of(
                "pub mod models {",
                "    use serde::{Deserialize, Serialize};",
                ""));
        List<Shape> shapes = SdkCodegen.dataShapesInNamespace(model, namespace);

        for (Shape shape : shapes) {
            if (isSimpleAlias(shape)) {
                lines.add("    pub type " + rustTypeName(shape.getId().getName()) + " = "
                        + rustPreludeType(preludeEquivalent(shape)) + ";");
                lines.add("");
            } else if (shape.isEnumShape()) {
                lines.addAll(renderEnum(shape.asEnumShape().orElseThrow()));
            } else if (shape.isListShape()) {
                CollectionShape list = shape.asListShape().orElseThrow();
                lines.add("    pub type " + rustTypeName(shape.getId().getName()) + " = Vec<"
                        + rustTargetType(list.getMember().getTarget()) + ">;");
                lines.add("");
            } else if (shape.isMapShape()) {
                MapShape map = shape.asMapShape().orElseThrow();
                lines.add("    pub type " + rustTypeName(shape.getId().getName())
                        + " = std::collections::BTreeMap<" + rustTargetType(map.getKey().getTarget())
                        + ", " + rustTargetType(map.getValue().getTarget()) + ">;");
                lines.add("");
            } else if (shape.isStructureShape()) {
                lines.addAll(renderStructure(shape));
            } else if (shape.isUnionShape()) {
                lines.addAll(renderUnion(shape));
            }
        }
        if (lines.get(lines.size() - 1).isEmpty()) {
            lines.remove(lines.size() - 1);
        }
        lines.add("}");
        return lines;
    }

    private static List<String> renderEnum(EnumShape shape) {
        List<String> lines = new ArrayList<>(List.of(
                "    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]",
                "    pub enum " + rustTypeName(shape.getId().getName()) + " {"));
        Set<String> used = new HashSet<>();
        List<EnumVariant> variants = new ArrayList<>();
        for (MemberShape member : shape.getAllMembers().values()) {
            String literal = enumLiteral(member);
            String name = rustVariantName(member.getMemberName(), literal);
            String base = name;
            int suffix = 2;
            while (!used.add(name)) {
                name = base + suffix++;
            }
            variants.add(new EnumVariant(name, literal));
            lines.add("        #[serde(rename = " + rustString(literal) + ")]");
            lines.add("        " + name + ",");
        }
        lines.add("    }");
        lines.add("");
        lines.add("    impl " + rustTypeName(shape.getId().getName()) + " {");
        lines.add("        pub const fn as_str(&self) -> &'static str {");
        lines.add("            match self {");
        for (EnumVariant variant : variants) {
            lines.add("                Self::" + variant.name() + " => " + rustString(variant.literal()) + ",");
        }
        lines.add("            }");
        lines.add("        }");
        lines.add("    }");
        lines.add("");
        return lines;
    }

    private static List<String> renderStructure(Shape shape) {
        List<String> lines = new ArrayList<>(List.of(
                "    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]",
                "    pub struct " + rustTypeName(shape.getId().getName()) + " {"));
        for (MemberShape member : shape.members()) {
            lines.add("        #[serde(rename = " + rustString(jsonName(member))
                    + (member.isRequired() ? ")]" : ", skip_serializing_if = \"Option::is_none\")]"));
            String type = rustTargetType(member.getTarget());
            lines.add("        pub " + rustMemberName(member) + ": "
                    + (member.isRequired() ? type : "Option<" + type + ">") + ",");
        }
        lines.add("    }");
        lines.add("");
        return lines;
    }

    private static List<String> renderUnion(Shape shape) {
        List<String> lines = new ArrayList<>(List.of(
                "    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]",
                "    #[serde(untagged)]",
                "    pub enum " + rustTypeName(shape.getId().getName()) + " {"));
        Set<String> used = new HashSet<>();
        for (MemberShape member : shape.members()) {
            String name = rustVariantName(member.getMemberName(), member.getMemberName());
            String base = name;
            int suffix = 2;
            while (!used.add(name)) {
                name = base + suffix++;
            }
            lines.add("        #[serde(rename = " + rustString(jsonName(member)) + ")]");
            lines.add("        " + name + "(" + rustTargetType(member.getTarget()) + "),");
        }
        lines.add("    }");
        lines.add("");
        return lines;
    }

    private static List<String> renderBuilder(Model model, OperationShape operation) {
        List<String> lines = new ArrayList<>();
        HttpTrait http = operation.expectTrait(HttpTrait.class);
        String operationName = operation.getId().getName();
        String functionName = "build_" + toSnake(operationName);
        String inputParameter = inputMembers(model, operation).isEmpty() ? "_input" : "input";
        String signature = operation.getInput()
                .map(id -> "fn " + functionName + "(base_url: &str, " + inputParameter + ": "
                        + rustTypeName(id.getName()) + ") -> Result<Request, Error> {")
                .orElse("fn " + functionName + "(base_url: &str) -> Result<Request, Error> {");
        lines.add(signature);
        lines.add("    let mut url = UrlBuilder::new(base_url)?;");
        Map<String, MemberShape> membersByName = inputMembersByName(model, operation);
        for (PathPart part : pathParts(http.getUri().toString())) {
            if (part.kind() == PathPartKind.LITERAL) {
                lines.add("    url.path_literal(" + rustString(part.value()) + ");");
            } else {
                lines.add("    " + rustPathCall(model, membersByName.get(part.value())) + ";");
            }
        }
        for (MemberShape member : inputMembers(model, operation)) {
            if (member.hasTrait(HttpQueryTrait.class)) {
                lines.addAll(rustQueryCalls(model, member));
            }
        }
        lines.add("    Ok(Request {");
        lines.add("        operation: " + rustString(operationName) + ",");
        lines.add("        method: Method::" + rustMethod(http.getMethod()) + ",");
        lines.add("        url: url.finish(),");
        lines.add("        body: " + rustPayload(model, operation) + ",");
        lines.add("        expected_status: " + http.getCode() + ",");
        lines.add("    })");
        lines.add("}");
        return lines;
    }

    private static List<String> renderResourceClients(
            Model model,
            List<SdkCodegen.OperationBinding> bindings,
            List<ResourceShape> resources,
            List<ResourceShape> topLevelResources
    ) {
        List<String> lines = new ArrayList<>();
        for (ResourceShape resource : resources) {
            String clientType = resourceClientType(resource);
            lines.add("pub struct " + clientType + "<'a> {");
            lines.add("    client: &'a Client,");
            lines.add("}");
            lines.add("");
        }
        for (ResourceShape resource : topLevelResources) {
            String clientType = resourceClientType(resource);
            String accessor = toSnake(SdkCodegen.resourceAccessorName(resource));
            lines.add("impl Client {");
            lines.add("    pub fn " + accessor + "(&self) -> " + clientType + "<'_> {");
            lines.add("        " + clientType + " { client: self }");
            lines.add("    }");
            lines.add("}");
            lines.add("");
        }

        Map<ShapeId, ResourceShape> parents = resourceParents(resources);
        for (ResourceShape resource : resources) {
            ResourceShape parent = parents.get(resource.getId());
            if (parent == null) {
                continue;
            }
            String parentType = resourceClientType(parent);
            String childType = resourceClientType(resource);
            String accessor = toSnake(SdkCodegen.resourceAccessorName(resource));
            lines.add("impl " + parentType + "<'_> {");
            lines.add("    pub fn " + accessor + "(&self) -> " + childType + "<'_> {");
            lines.add("        " + childType + " { client: self.client }");
            lines.add("    }");
            lines.add("}");
            lines.add("");
        }

        for (SdkCodegen.OperationBinding binding : bindings) {
            OperationShape operation = binding.operation();
            String method = toSnake(binding.methodName());
            String output = operation.getOutput()
                    .map(id -> rustTargetType(id))
                    .orElse("()");
            MemberShape outputPayload = outputPayload(model, operation);
            if (binding.isServiceOperation()) {
                lines.add("impl Client {");
            } else {
                lines.add("impl " + resourceClientType(binding.resource()) + "<'_> {");
            }
            String receiver = binding.isServiceOperation() ? "self" : "self.client";
            if (operation.getInput().isPresent()) {
                String input = rustTypeName(operation.getInput().orElseThrow().getName());
                lines.add("    pub fn " + method + "(&self, input: " + input + ") -> Result<" + output + ", Error> {");
                lines.add("        let request = build_" + toSnake(operation.getId().getName())
                        + "(" + receiver + ".base_url(), input)?;");
            } else {
                lines.add("    pub fn " + method + "(&self) -> Result<" + output + ", Error> {");
                lines.add("        let request = build_" + toSnake(operation.getId().getName())
                        + "(" + receiver + ".base_url())?;");
            }
            if (outputPayload == null) {
                lines.add("        " + receiver + ".execute(request)");
            } else {
                String payloadType = rustTargetType(outputPayload.getTarget());
                String execute = outputPayload.isRequired() ? "execute" : "execute_optional";
                lines.add("        let body = " + receiver + "." + execute + "::<" + payloadType + ">(request)?;");
                lines.add("        Ok(" + output + " { " + rustMemberName(outputPayload) + ": body })");
            }
            lines.add("    }");
            lines.add("}");
            lines.add("");
        }
        if (!lines.isEmpty() && lines.get(lines.size() - 1).isEmpty()) {
            lines.remove(lines.size() - 1);
        }
        return lines;
    }

    private static Map<ShapeId, ResourceShape> resourceParents(List<ResourceShape> resources) {
        Map<ShapeId, ResourceShape> result = new LinkedHashMap<>();
        for (ResourceShape parent : resources) {
            for (ShapeId child : parent.getResources()) {
                result.put(child, parent);
            }
        }
        return result;
    }

    private static MemberShape outputPayload(Model model, OperationShape operation) {
        if (operation.getOutput().isEmpty()) {
            return null;
        }
        Shape output = model.expectShape(operation.getOutput().orElseThrow());
        for (MemberShape member : output.members()) {
            if (member.hasTrait(HttpPayloadTrait.class)) {
                return member;
            }
        }
        return null;
    }

    private static String resourceClientType(ResourceShape resource) {
        return rustTypeName(SdkCodegen.resourceAccessorName(resource)) + "ResourceClient";
    }

    private static List<MemberShape> inputMembers(Model model, OperationShape operation) {
        return operation.getInput()
                .map(id -> new ArrayList<>(model.expectShape(id).members()))
                .orElseGet(ArrayList::new);
    }

    private static Map<String, MemberShape> inputMembersByName(Model model, OperationShape operation) {
        Map<String, MemberShape> result = new LinkedHashMap<>();
        for (MemberShape member : inputMembers(model, operation)) {
            result.put(member.getMemberName(), member);
        }
        return result;
    }

    private static String rustPathCall(Model model, MemberShape member) {
        if (member == null) {
            throw new IllegalStateException("Missing input member for path label");
        }
        String field = "input." + rustMemberName(member);
        return switch (scalarKind(model, member.getTarget())) {
            case INTEGER -> "url.path_i64(" + field + " as i64)";
            case FLOAT -> "url.path_f64(" + field + " as f64)";
            case BOOLEAN -> "url.path_bool(" + field + ")";
            case STRING -> "url.path_string(" + rustStringReference(model, member.getTarget(), "&" + field) + ")";
        };
    }

    private static List<String> rustQueryCalls(Model model, MemberShape member) {
        String query = rustString(member.expectTrait(HttpQueryTrait.class).getValue());
        String field = "input." + rustMemberName(member);
        Shape target = model.expectShape(member.getTarget());
        List<String> lines = new ArrayList<>();
        if (target.isListShape()) {
            ShapeId inner = target.asListShape().orElseThrow().getMember().getTarget();
            if (member.isRequired()) {
                lines.add("    for value in &" + field + " {");
                lines.add("        " + rustQueryCall(model, inner, query, "value", true) + ";");
                lines.add("    }");
            } else {
                lines.add("    if let Some(values) = " + field + ".as_ref() {");
                lines.add("        for value in values {");
                lines.add("            " + rustQueryCall(model, inner, query, "value", true) + ";");
                lines.add("        }");
                lines.add("    }");
            }
            return lines;
        }

        if (member.isRequired()) {
            lines.add("    " + rustQueryCall(model, member.getTarget(), query, field, false) + ";");
        } else {
            lines.add("    if let Some(value) = " + field + ".as_ref() {");
            lines.add("        " + rustQueryCall(model, member.getTarget(), query, "value", true) + ";");
            lines.add("    }");
        }
        return lines;
    }

    private static String rustQueryCall(
            Model model,
            ShapeId target,
            String query,
            String expression,
            boolean reference
    ) {
        return switch (scalarKind(model, target)) {
            case INTEGER -> "url.query_i64(" + query + ", " + (reference ? "*" : "") + expression + " as i64)";
            case FLOAT -> "url.query_f64(" + query + ", " + (reference ? "*" : "") + expression + " as f64)";
            case BOOLEAN -> "url.query_bool(" + query + ", " + (reference ? "*" : "") + expression + ")";
            case STRING -> "url.query_string(" + query + ", "
                    + rustStringReference(model, target, reference ? expression : "&" + expression) + ")";
        };
    }

    private static String rustStringReference(Model model, ShapeId target, String reference) {
        Shape shape = model.expectShape(target);
        return shape.isEnumShape() ? reference + ".as_str()" : reference;
    }

    private static ScalarKind scalarKind(Model model, ShapeId target) {
        Shape shape = model.expectShape(target);
        if (shape.isEnumShape()) {
            return ScalarKind.STRING;
        }
        return switch (shape.getType()) {
            case BYTE, SHORT, INTEGER, LONG, BIG_INTEGER -> ScalarKind.INTEGER;
            case FLOAT, DOUBLE, BIG_DECIMAL -> ScalarKind.FLOAT;
            case BOOLEAN -> ScalarKind.BOOLEAN;
            default -> ScalarKind.STRING;
        };
    }

    private static String rustPayload(Model model, OperationShape operation) {
        for (MemberShape member : inputMembers(model, operation)) {
            if (member.hasTrait(HttpPayloadTrait.class)) {
                String field = "input." + rustMemberName(member);
                if (member.isRequired()) {
                    return "Some(serde_json::to_vec(&" + field + ").map_err(Error::serialize)?)";
                }
                return field + ".as_ref().map(serde_json::to_vec).transpose().map_err(Error::serialize)?";
            }
        }
        return "None";
    }

    private static boolean isSimpleAlias(Shape shape) {
        return switch (shape.getType()) {
            case STRING, BYTE, SHORT, INTEGER, LONG, FLOAT, DOUBLE, BIG_INTEGER, BIG_DECIMAL,
                    BOOLEAN, BLOB, TIMESTAMP, DOCUMENT -> true;
            default -> false;
        };
    }

    private static ShapeId preludeEquivalent(Shape shape) {
        return ShapeId.from("smithy.api#" + switch (shape.getType()) {
            case STRING -> "String";
            case BYTE -> "Byte";
            case SHORT -> "Short";
            case INTEGER -> "Integer";
            case LONG -> "Long";
            case FLOAT -> "Float";
            case DOUBLE -> "Double";
            case BIG_INTEGER -> "BigInteger";
            case BIG_DECIMAL -> "BigDecimal";
            case BOOLEAN -> "Boolean";
            case BLOB -> "Blob";
            case TIMESTAMP -> "Timestamp";
            case DOCUMENT -> "Document";
            default -> throw new IllegalArgumentException("Not a simple alias: " + shape.getId());
        });
    }

    private static String rustTargetType(ShapeId target) {
        return target.getNamespace().equals("smithy.api")
                ? rustPreludeType(target)
                : rustTypeName(target.getName());
    }

    private static String rustPreludeType(ShapeId target) {
        return switch (target.getName()) {
            case "String", "Timestamp", "BigInteger", "BigDecimal" -> "String";
            case "Byte" -> "i8";
            case "Short" -> "i16";
            case "Integer" -> "i32";
            case "Long" -> "i64";
            case "Float" -> "f32";
            case "Double" -> "f64";
            case "Boolean" -> "bool";
            case "Blob" -> "Vec<u8>";
            case "Document" -> "serde_json::Value";
            default -> rustTypeName(target.getName());
        };
    }

    private static List<PathPart> pathParts(String uri) {
        List<PathPart> parts = new ArrayList<>();
        int pos = 0;
        Matcher matcher = PATH_LABEL.matcher(uri);
        while (matcher.find()) {
            if (matcher.start() > pos) {
                parts.add(new PathPart(PathPartKind.LITERAL, uri.substring(pos, matcher.start())));
            }
            parts.add(new PathPart(PathPartKind.LABEL, matcher.group(1)));
            pos = matcher.end();
        }
        if (pos < uri.length()) {
            parts.add(new PathPart(PathPartKind.LITERAL, uri.substring(pos)));
        }
        return parts;
    }

    private static String rustMethod(String method) {
        return switch (method.toUpperCase(Locale.ROOT)) {
            case "DELETE" -> "Delete";
            case "HEAD" -> "Head";
            case "PATCH" -> "Patch";
            case "POST" -> "Post";
            case "PUT" -> "Put";
            default -> "Get";
        };
    }

    private static String jsonName(MemberShape member) {
        return member.getTrait(JsonNameTrait.class).map(JsonNameTrait::getValue).orElse(member.getMemberName());
    }

    private static String enumLiteral(MemberShape member) {
        return member.getTrait(EnumValueTrait.class).flatMap(EnumValueTrait::getStringValue)
                .orElse(member.getMemberName());
    }

    private static String rustMemberName(MemberShape member) {
        return rustSafeName(toSnake(member.getMemberName()));
    }

    private static String rustTypeName(String value) {
        String result = toPascal(value);
        return result.isEmpty() ? "Value" : result;
    }

    private static String rustVariantName(String memberName, String literal) {
        String result = toPascal(memberName);
        if (result.isEmpty()) {
            result = toPascal(literal);
        }
        if (result.isEmpty()) {
            result = "Value";
        }
        if (Character.isDigit(result.charAt(0))) {
            result = "Value" + result;
        }
        return result;
    }

    private static String toPascal(String value) {
        String words = value.replaceAll("(.)([A-Z][a-z]+)", "$1 $2")
                .replaceAll("([a-z0-9])([A-Z])", "$1 $2")
                .replace('_', ' ');
        Matcher matcher = Pattern.compile("[A-Za-z]+|[0-9]+").matcher(words);
        StringBuilder result = new StringBuilder();
        while (matcher.find()) {
            String part = matcher.group();
            result.append(part.substring(0, 1).toUpperCase(Locale.ROOT));
            if (part.length() > 1) {
                result.append(part.substring(1).toLowerCase(Locale.ROOT));
            }
        }
        return result.toString();
    }

    private static String toSnake(String value) {
        String first = value.replaceAll("(.)([A-Z][a-z]+)", "$1_$2");
        return rustSafeName(first.replaceAll("([a-z0-9])([A-Z])", "$1_$2").toLowerCase(Locale.ROOT));
    }

    private static String rustSafeName(String value) {
        return RUST_KEYWORDS.contains(value) ? value + "_" : value;
    }

    private static String rustString(String value) {
        return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }

    private record EnumVariant(String name, String literal) {}

    private record PathPart(PathPartKind kind, String value) {}

    private enum PathPartKind { LITERAL, LABEL }

    private enum ScalarKind { STRING, INTEGER, FLOAT, BOOLEAN }
}
