package com.github.its_felix.superhuman_docs_sdk.smithy.codegen;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.ShapeType;
import software.amazon.smithy.model.traits.HttpLabelTrait;
import software.amazon.smithy.model.traits.HttpPayloadTrait;
import software.amazon.smithy.model.traits.HttpQueryTrait;
import software.amazon.smithy.model.traits.HttpTrait;

final class RustRenderer {
    private static final Pattern PATH_LABEL = Pattern.compile("\\{([A-Za-z_][A-Za-z0-9_]*)}");
    private static final Set<String> RUST_KEYWORDS = Set.of(
            "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
            "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
            "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
            "where", "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final",
            "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try");

    private RustRenderer() {}

    static String render(Model model, List<OperationShape> operations) {
        List<String> lines = new ArrayList<>(List.of(
                "// Code generated by smithy/generator; DO NOT EDIT.",
                "",
                "use crate::core::{Error, Method, Request, UrlBuilder};",
                "",
                "pub const OPERATION_COUNT: usize = " + operations.size() + ";",
                ""));

        Set<ShapeId> emittedInputs = new HashSet<>();
        for (OperationShape operation : operations) {
            if (operation.getInput().isEmpty() || !emittedInputs.add(operation.getInput().orElseThrow())) {
                continue;
            }
            lines.addAll(renderInputStruct(model, operation));
            lines.add("");
        }

        for (OperationShape operation : operations) {
            lines.addAll(renderBuilder(model, operation));
            lines.add("");
        }

        lines.add("#[cfg(test)]");
        lines.add("mod tests {");
        lines.add("    use super::*;");
        lines.add("");
        lines.add("    #[test]");
        lines.add("    fn generated_operation_count_tracks_smithy_service() {");
        lines.add("        assert_eq!(OPERATION_COUNT, " + operations.size() + ");");
        lines.add("    }");
        lines.add("}");
        lines.add("");
        return String.join("\n", lines);
    }

    private static List<String> renderInputStruct(Model model, OperationShape operation) {
        List<MemberShape> members = boundInputMembers(model, operation);
        List<String> lines = new ArrayList<>();
        String name = operation.getInput().orElseThrow().getName();
        lines.add("#[derive(Clone, Debug, Default, PartialEq)]");
        lines.add("pub struct " + name + " {");
        for (MemberShape member : members) {
            lines.add("    pub " + rustMemberName(member) + ": " + rustFieldType(model, member) + ",");
        }
        lines.add("}");
        return lines;
    }

    private static List<String> renderBuilder(Model model, OperationShape operation) {
        List<String> lines = new ArrayList<>();
        HttpTrait http = operation.expectTrait(HttpTrait.class);
        String operationName = operation.getId().getName();
        String functionName = "build_" + toSnake(operationName);
        String signature = operation.getInput()
                .map(id -> "pub fn " + functionName + "(base_url: &str, input: " + id.getName() + ") -> Result<Request, Error> {")
                .orElse("pub fn " + functionName + "(base_url: &str) -> Result<Request, Error> {");
        lines.add(signature);
        lines.add("    let mut url = UrlBuilder::new(base_url)?;");
        Map<String, MemberShape> membersByName = inputMembersByName(model, operation);
        for (PathPart part : pathParts(http.getUri().toString())) {
            if (part.kind() == PathPartKind.LITERAL) {
                lines.add("    url.path_literal(" + rustString(part.value()) + ");");
            } else {
                MemberShape member = membersByName.get(part.value());
                lines.add("    " + rustPathCall(model, member) + ";");
            }
        }
        for (MemberShape member : inputMembers(model, operation)) {
            if (member.hasTrait(HttpQueryTrait.class)) {
                lines.addAll(rustQueryCalls(model, member));
            }
        }
        lines.add("    Ok(Request {");
        lines.add("        operation: " + rustString(operationName) + ",");
        lines.add("        method: Method::" + rustMethod(http.getMethod()) + ",");
        lines.add("        url: url.finish(),");
        lines.add("        body: " + rustPayload(model, operation) + ",");
        lines.add("        expected_status: " + http.getCode() + ",");
        lines.add("    })");
        lines.add("}");
        return lines;
    }

    private static List<MemberShape> inputMembers(Model model, OperationShape operation) {
        return operation.getInput()
                .map(id -> new ArrayList<>(model.expectShape(id).members()))
                .orElseGet(ArrayList::new);
    }

    private static List<MemberShape> boundInputMembers(Model model, OperationShape operation) {
        return inputMembers(model, operation).stream()
                .filter(member -> member.hasTrait(HttpLabelTrait.class)
                        || member.hasTrait(HttpQueryTrait.class)
                        || member.hasTrait(HttpPayloadTrait.class))
                .toList();
    }

    private static Map<String, MemberShape> inputMembersByName(Model model, OperationShape operation) {
        Map<String, MemberShape> result = new LinkedHashMap<>();
        for (MemberShape member : inputMembers(model, operation)) {
            result.put(member.getMemberName(), member);
        }
        return result;
    }

    private static String rustFieldType(Model model, MemberShape member) {
        String base;
        Shape target = model.expectShape(member.getTarget());
        if (member.hasTrait(HttpPayloadTrait.class)) {
            base = "String";
        } else if (target.isListShape()) {
            ShapeId inner = target.asListShape().orElseThrow().getMember().getTarget();
            base = "Vec<" + rustScalarType(inner) + ">";
        } else {
            base = rustScalarType(member.getTarget());
        }
        return member.isRequired() ? base : "Option<" + base + ">";
    }

    private static String rustScalarType(ShapeId shape) {
        return switch (shape.getName()) {
            case "Boolean" -> "bool";
            case "Integer", "Long" -> "i64";
            case "Double", "Float" -> "f64";
            default -> "String";
        };
    }

    private static String rustPathCall(Model model, MemberShape member) {
        if (member == null) {
            throw new IllegalStateException("Missing input member for path label");
        }
        String field = "input." + rustMemberName(member);
        Shape target = model.expectShape(member.getTarget());
        ShapeType type = isSimpleAlias(target) ? target.getType() : member.getTarget().getName().equals("String")
                ? ShapeType.STRING
                : target.getType();
        return switch (type) {
            case INTEGER, LONG -> "url.path_i64(" + field + ")";
            case DOUBLE, FLOAT -> "url.path_f64(" + field + ")";
            case BOOLEAN -> "url.path_bool(" + field + ")";
            default -> "url.path_string(&" + field + ")";
        };
    }

    private static List<String> rustQueryCalls(Model model, MemberShape member) {
        String query = rustString(member.expectTrait(HttpQueryTrait.class).getValue());
        String field = "input." + rustMemberName(member);
        Shape target = model.expectShape(member.getTarget());
        List<String> lines = new ArrayList<>();
        if (target.isListShape()) {
            ShapeId inner = target.asListShape().orElseThrow().getMember().getTarget();
            String call = rustQueryMethod(inner);
            if (member.isRequired()) {
                lines.add("    for value in &" + field + " {");
            } else {
                lines.add("    if let Some(values) = " + field + ".as_ref() {");
                lines.add("        for value in values {");
            }
            String value = rustScalarType(inner).equals("String") ? "value" : "*value";
            lines.add("            url." + call + "(" + query + ", " + value + ");");
            if (member.isRequired()) {
                lines.add("    }");
            } else {
                lines.add("        }");
                lines.add("    }");
            }
            return lines;
        }

        String call = rustQueryMethod(member.getTarget());
        if (member.isRequired()) {
            lines.add("    url." + call + "(" + query + ", " + rustQueryValue(member.getTarget(), field) + ");");
        } else {
            String value = rustScalarType(member.getTarget()).equals("String") ? "value" : "*value";
            lines.add("    if let Some(value) = " + field + ".as_ref() {");
            lines.add("        url." + call + "(" + query + ", " + value + ");");
            lines.add("    }");
        }
        return lines;
    }

    private static String rustQueryMethod(ShapeId shape) {
        return switch (shape.getName()) {
            case "Boolean" -> "query_bool";
            case "Integer", "Long" -> "query_i64";
            case "Double", "Float" -> "query_f64";
            default -> "query_string";
        };
    }

    private static String rustQueryValue(ShapeId shape, String field) {
        return rustScalarType(shape).equals("String") ? "&" + field : field;
    }

    private static String rustPayload(Model model, OperationShape operation) {
        for (MemberShape member : inputMembers(model, operation)) {
            if (member.hasTrait(HttpPayloadTrait.class)) {
                String field = "input." + rustMemberName(member);
                return member.isRequired() ? "Some(" + field + ")" : field;
            }
        }
        return "None";
    }

    private static boolean isSimpleAlias(Shape shape) {
        return switch (shape.getType()) {
            case STRING, INTEGER, LONG, DOUBLE, BOOLEAN, BLOB, TIMESTAMP, DOCUMENT -> true;
            default -> false;
        };
    }

    private static List<PathPart> pathParts(String uri) {
        List<PathPart> parts = new ArrayList<>();
        int pos = 0;
        Matcher matcher = PATH_LABEL.matcher(uri);
        while (matcher.find()) {
            if (matcher.start() > pos) {
                parts.add(new PathPart(PathPartKind.LITERAL, uri.substring(pos, matcher.start())));
            }
            parts.add(new PathPart(PathPartKind.LABEL, matcher.group(1)));
            pos = matcher.end();
        }
        if (pos < uri.length()) {
            parts.add(new PathPart(PathPartKind.LITERAL, uri.substring(pos)));
        }
        return parts;
    }

    private static String rustMethod(String method) {
        return switch (method.toUpperCase(Locale.ROOT)) {
            case "DELETE" -> "Delete";
            case "HEAD" -> "Head";
            case "PATCH" -> "Patch";
            case "POST" -> "Post";
            case "PUT" -> "Put";
            default -> "Get";
        };
    }

    private static String rustMemberName(MemberShape member) {
        return rustSafeName(toSnake(member.getMemberName()));
    }

    private static String toSnake(String value) {
        String first = value.replaceAll("(.)([A-Z][a-z]+)", "$1_$2");
        return first.replaceAll("([a-z0-9])([A-Z])", "$1_$2").toLowerCase(Locale.ROOT);
    }

    private static String rustSafeName(String value) {
        return RUST_KEYWORDS.contains(value) ? value + "_" : value;
    }

    private static String rustString(String value) {
        return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }

    private record PathPart(PathPartKind kind, String value) {}

    private enum PathPartKind {
        LITERAL,
        LABEL
    }
}
