package com.github.its_felix.superhuman_docs_sdk.smithy.codegen;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.ShapeType;
import software.amazon.smithy.model.traits.HttpLabelTrait;
import software.amazon.smithy.model.traits.HttpPayloadTrait;
import software.amazon.smithy.model.traits.HttpQueryTrait;
import software.amazon.smithy.model.traits.HttpTrait;

final class ZigRenderer {
    private static final Pattern PATH_LABEL = Pattern.compile("\\{([A-Za-z_][A-Za-z0-9_]*)}");

    private ZigRenderer() {}

    static String render(Model model, List<OperationShape> operations) {
        List<String> lines = new ArrayList<>(List.of(
                "// Code generated by smithy/generator; DO NOT EDIT.",
                "",
                "const std = @import(\"std\");",
                "const core = @import(\"../core.zig\");",
                "",
                "const Allocator = std.mem.Allocator;",
                "",
                "pub const operation_count = " + operations.size() + ";",
                ""));

        Set<ShapeId> emittedInputs = new HashSet<>();
        for (OperationShape operation : operations) {
            if (operation.getInput().isEmpty() || !emittedInputs.add(operation.getInput().orElseThrow())) {
                continue;
            }
            String shapeName = operation.getInput().orElseThrow().getName();
            lines.add("pub const " + shapeName + " = struct {");
            List<MemberShape> members = inputMembers(model, operation);
            if (members.isEmpty()) {
                lines.add("};");
                lines.add("");
                continue;
            }
            for (MemberShape member : members) {
                if (member.hasTrait(HttpLabelTrait.class)
                        || member.hasTrait(HttpQueryTrait.class)
                        || member.hasTrait(HttpPayloadTrait.class)) {
                    lines.add("    " + member.getMemberName() + ": " + zigFieldType(model, member) + zigDefaultSuffix(member) + ",");
                }
            }
            lines.add("};");
            lines.add("");
        }

        for (OperationShape operation : operations) {
            String inputType = operation.getInput().map(ShapeId::getName).orElse("void");
            String inputArg = operation.getInput().isPresent() ? "input: " + inputType : "_: void";
            lines.add("pub fn build" + operation.getId().getName()
                    + "(allocator: Allocator, base_url: []const u8, " + inputArg + ") !core.Request {");
            lines.add("    var url = core.UrlBuilder.init(allocator);");
            lines.add("    errdefer url.deinit();");
            lines.add("    try url.base(base_url);");
            Map<String, MemberShape> membersByName = inputMembersByName(model, operation);
            for (PathPart part : pathParts(operation.expectTrait(HttpTrait.class).getUri().toString())) {
                if (part.kind() == PathPartKind.LITERAL) {
                    lines.add("    try url.pathLiteral(" + zigString(part.value()) + ");");
                } else {
                    MemberShape member = membersByName.get(part.value());
                    lines.add("    try url." + zigPathHelper(model, member) + "(input." + part.value() + ");");
                }
            }
            for (MemberShape member : inputMembers(model, operation)) {
                if (member.hasTrait(HttpQueryTrait.class)) {
                    lines.add("    try url." + zigQueryHelper(model, member) + "("
                            + zigString(member.expectTrait(HttpQueryTrait.class).getValue()) + ", input."
                            + member.getMemberName() + ");");
                }
            }
            String payload = "null";
            for (MemberShape member : inputMembers(model, operation)) {
                if (member.hasTrait(HttpPayloadTrait.class)) {
                    payload = member.isRequired()
                            ? "input." + member.getMemberName()
                            : "(input." + member.getMemberName() + " orelse null)";
                    break;
                }
            }
            HttpTrait http = operation.expectTrait(HttpTrait.class);
            lines.add("    return .{");
            lines.add("        .operation = " + zigString(operation.getId().getName()) + ",");
            lines.add("        .method = ." + http.getMethod() + ",");
            lines.add("        .url = try url.finish(),");
            lines.add("        .body = " + payload + ",");
            lines.add("        .expected_status = " + http.getCode() + ",");
            lines.add("    };");
            lines.add("}");
            lines.add("");
        }

        lines.add("test \"generated operation count tracks Smithy service\" {");
        lines.add("    try std.testing.expectEqual(@as(usize, " + operations.size() + "), operation_count);");
        lines.add("}");
        lines.add("");
        return String.join("\n", lines);
    }

    private static List<MemberShape> inputMembers(Model model, OperationShape operation) {
        return operation.getInput()
                .map(id -> new ArrayList<>(model.expectShape(id).members()))
                .orElseGet(ArrayList::new);
    }

    private static Map<String, MemberShape> inputMembersByName(Model model, OperationShape operation) {
        Map<String, MemberShape> result = new LinkedHashMap<>();
        for (MemberShape member : inputMembers(model, operation)) {
            result.put(member.getMemberName(), member);
        }
        return result;
    }

    private static boolean isSimpleAlias(Shape shape) {
        return switch (shape.getType()) {
            case STRING, INTEGER, LONG, DOUBLE, BOOLEAN, BLOB, TIMESTAMP, DOCUMENT -> true;
            default -> false;
        };
    }

    private static String zigFieldType(Model model, MemberShape member) {
        String base;
        Shape target = model.expectShape(member.getTarget());
        if (member.hasTrait(HttpPayloadTrait.class)) {
            base = "[]const u8";
        } else if (target.isListShape()) {
            ShapeId inner = target.asListShape().orElseThrow().getMember().getTarget();
            base = switch (inner.getName()) {
                case "Integer", "Long" -> "[]const i64";
                case "Double", "Float" -> "[]const f64";
                case "Boolean" -> "[]const bool";
                default -> "[]const []const u8";
            };
        } else {
            base = zigScalarType(member.getTarget());
        }
        return member.isRequired() ? base : "?" + base;
    }

    private static String zigScalarType(ShapeId shape) {
        return switch (shape.getName()) {
            case "Boolean" -> "bool";
            case "Integer", "Long" -> "i64";
            case "Double", "Float" -> "f64";
            default -> "[]const u8";
        };
    }

    private static String zigDefaultSuffix(MemberShape member) {
        return member.isRequired() ? "" : " = null";
    }

    private static String zigQueryHelper(Model model, MemberShape member) {
        Shape target = model.expectShape(member.getTarget());
        if (target.isListShape()) {
            ShapeId inner = target.asListShape().orElseThrow().getMember().getTarget();
            return switch (inner.getName()) {
                case "Integer", "Long" -> member.isRequired() ? "queryIntList" : "queryOptionalIntList";
                case "Double", "Float" -> member.isRequired() ? "queryFloatList" : "queryOptionalFloatList";
                case "Boolean" -> member.isRequired() ? "queryBoolList" : "queryOptionalBoolList";
                default -> member.isRequired() ? "queryStringList" : "queryOptionalStringList";
            };
        }
        return switch (member.getTarget().getName()) {
            case "Boolean" -> member.isRequired() ? "queryBool" : "queryOptionalBool";
            case "Integer", "Long" -> member.isRequired() ? "queryInt" : "queryOptionalInt";
            case "Double", "Float" -> member.isRequired() ? "queryFloat" : "queryOptionalFloat";
            default -> member.isRequired() ? "queryString" : "queryOptionalString";
        };
    }

    private static String zigPathHelper(Model model, MemberShape member) {
        if (member == null) {
            throw new IllegalStateException("Missing input member for path label");
        }
        Shape target = model.expectShape(member.getTarget());
        ShapeType type = isSimpleAlias(target) ? target.getType() : member.getTarget().getName().equals("String")
                ? ShapeType.STRING
                : target.getType();
        return switch (type) {
            case INTEGER, LONG -> "pathInt";
            case DOUBLE, FLOAT -> "pathFloat";
            case BOOLEAN -> "pathBool";
            default -> "pathString";
        };
    }

    private static List<PathPart> pathParts(String uri) {
        List<PathPart> parts = new ArrayList<>();
        int pos = 0;
        Matcher matcher = PATH_LABEL.matcher(uri);
        while (matcher.find()) {
            if (matcher.start() > pos) {
                parts.add(new PathPart(PathPartKind.LITERAL, uri.substring(pos, matcher.start())));
            }
            parts.add(new PathPart(PathPartKind.LABEL, matcher.group(1)));
            pos = matcher.end();
        }
        if (pos < uri.length()) {
            parts.add(new PathPart(PathPartKind.LITERAL, uri.substring(pos)));
        }
        return parts;
    }

    private static String zigString(String value) {
        return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }

    private record PathPart(PathPartKind kind, String value) {}

    private enum PathPartKind {
        LITERAL,
        LABEL
    }
}
