package com.github.its_felix.superhuman_docs_sdk.smithy.codegen;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.shapes.CollectionShape;
import software.amazon.smithy.model.shapes.EnumShape;
import software.amazon.smithy.model.shapes.MapShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ResourceShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.ShapeType;
import software.amazon.smithy.model.traits.EnumValueTrait;
import software.amazon.smithy.model.traits.HttpPayloadTrait;
import software.amazon.smithy.model.traits.HttpQueryTrait;
import software.amazon.smithy.model.traits.HttpTrait;
import software.amazon.smithy.model.traits.JsonNameTrait;

final class ZigRenderer {
    private static final Pattern PATH_LABEL = Pattern.compile("\\{([A-Za-z_][A-Za-z0-9_]*)}");
    private static final Set<String> ZIG_KEYWORDS = Set.of(
            "addrspace", "align", "allowzero", "and", "anyframe", "anytype", "asm", "async",
            "await", "break", "callconv", "catch", "comptime", "const", "continue", "defer",
            "else", "enum", "errdefer", "error", "export", "extern", "fn", "for", "if", "inline",
            "linksection", "noalias", "noinline", "nosuspend", "opaque", "or", "orelse", "packed",
            "pub", "resume", "return", "struct", "suspend", "switch", "test", "threadlocal", "try",
            "union", "unreachable", "usingnamespace", "var", "volatile", "while");

    private ZigRenderer() {}

    static String render(
            Model model,
            ServiceShape service,
            List<SdkCodegen.OperationBinding> bindings,
            List<ResourceShape> resources
    ) {
        List<String> lines = new ArrayList<>(List.of(
                "// Code generated by smithy/generator; DO NOT EDIT.",
                "",
                "const std = @import(\"std\");",
                "const core = @import(\"../core.zig\");",
                "",
                "const Allocator = std.mem.Allocator;",
                "",
                "pub const operation_count = " + bindings.size() + ";",
                "pub const ClientOptions = core.ClientOptions;",
                "pub const Transport = core.Transport;",
                ""));

        renderModels(lines, model, service.getId().getNamespace());
        renderClient(lines, model, service, bindings, resources);
        for (SdkCodegen.OperationBinding binding : bindings) {
            renderBuilder(lines, model, binding.operation());
            renderExecutor(lines, binding.operation());
        }

        lines.add("test \"generated operation count tracks Smithy service\" {");
        lines.add("    try std.testing.expectEqual(@as(usize, " + bindings.size() + "), operation_count);");
        lines.add("}");
        lines.add("");
        lines.add("test \"all generated declarations compile\" {");
        lines.add("    std.testing.refAllDecls(@This());");
        lines.add("    std.testing.refAllDecls(Client);");
        for (ResourceShape resource : resources) {
            lines.add("    std.testing.refAllDecls(" + resourceClientType(resource) + ");");
        }
        lines.add("}");
        lines.add("");
        return String.join("\n", lines);
    }

    private static void renderModels(List<String> lines, Model model, String namespace) {
        List<Shape> shapes = SdkCodegen.dataShapesInNamespace(model, namespace);

        for (Shape shape : shapes) {
            String name = zigIdentifier(shape.getId().getName());
            if (isSimpleAlias(shape)) {
                lines.add("pub const " + name + " = " + zigPreludeType(shape.getType()) + ";");
                lines.add("");
            } else if (shape.isEnumShape()) {
                EnumShape enumShape = shape.asEnumShape().orElseThrow();
                lines.add("pub const " + name + " = enum {");
                for (MemberShape member : enumShape.getAllMembers().values()) {
                    lines.add("    " + zigIdentifier(enumLiteral(member)) + ",");
                }
                lines.add("};");
                lines.add("");
            } else if (shape.isListShape()) {
                CollectionShape list = shape.asListShape().orElseThrow();
                lines.add("pub const " + name + " = []const " + zigTargetType(model, list.getMember().getTarget()) + ";");
                lines.add("");
            } else if (shape.isMapShape()) {
                MapShape map = shape.asMapShape().orElseThrow();
                lines.add("pub const " + name + " = std.json.ArrayHashMap("
                        + zigTargetType(model, map.getValue().getTarget()) + ");");
                lines.add("");
            } else if (shape.isStructureShape()) {
                lines.add("pub const " + name + " = struct {");
                for (MemberShape member : shape.members()) {
                    String type = zigTargetType(model, member.getTarget());
                    lines.add("    " + zigMemberIdentifier(member) + ": "
                            + (member.isRequired() ? type : "?" + type + " = null") + ",");
                }
                lines.add("};");
                lines.add("");
            } else if (shape.isUnionShape()) {
                lines.add("pub const " + name + " = union(enum) {");
                for (MemberShape member : shape.members()) {
                    lines.add("    " + zigMemberIdentifier(member) + ": "
                            + zigTargetType(model, member.getTarget()) + ",");
                }
                lines.add("};");
                lines.add("");
            }
        }
    }

    private static void renderClient(
            List<String> lines,
            Model model,
            ServiceShape service,
            List<SdkCodegen.OperationBinding> bindings,
            List<ResourceShape> resources
    ) {
        List<ResourceShape> topLevelResources = SdkCodegen.topLevelResourcesInServiceOrder(model, service);
        Map<ShapeId, List<SdkCodegen.OperationBinding>> byResource = new LinkedHashMap<>();
        for (ResourceShape resource : resources) {
            byResource.put(resource.getId(), new ArrayList<>());
        }
        List<SdkCodegen.OperationBinding> serviceBindings = new ArrayList<>();
        for (SdkCodegen.OperationBinding binding : bindings) {
            if (binding.isServiceOperation()) {
                serviceBindings.add(binding);
            } else {
                byResource.get(binding.resource().getId()).add(binding);
            }
        }

        lines.add("pub const Client = struct {");
        lines.add("    runtime: core.ClientCore,");
        lines.add("");
        lines.add("    pub fn init(allocator: Allocator, api_token: []const u8) !Client {");
        lines.add("        return .{ .runtime = try core.ClientCore.init(allocator, api_token) };");
        lines.add("    }");
        lines.add("");
        lines.add("    pub fn initWithOptions(allocator: Allocator, options: ClientOptions) !Client {");
        lines.add("        return .{ .runtime = try core.ClientCore.initWithOptions(allocator, options) };");
        lines.add("    }");
        lines.add("");
        lines.add("    pub fn deinit(self: *Client) void {");
        lines.add("        self.runtime.deinit();");
        lines.add("        self.* = undefined;");
        lines.add("    }");
        lines.add("");
        lines.add("    pub fn sendRequest(self: *Client, request: core.Request) !core.Response {");
        lines.add("        return self.runtime.sendRequest(request);");
        lines.add("    }");
        lines.add("");
        for (ResourceShape resource : topLevelResources) {
            String accessor = lowerFirst(SdkCodegen.resourceAccessorName(resource));
            String clientType = resourceClientType(resource);
            lines.add("    pub fn " + zigIdentifier(accessor) + "(self: *Client) " + clientType + " {");
            lines.add("        return .{ .client = self };");
            lines.add("    }");
            lines.add("");
        }
        for (SdkCodegen.OperationBinding binding : serviceBindings) {
            renderClientMethod(lines, model, binding, "*Client", "&self.runtime", 4);
        }
        lines.add("};");
        lines.add("");

        Map<ShapeId, ResourceShape> parents = SdkCodegen.resourceParents(model, service);
        for (ResourceShape resource : resources) {
            String clientType = resourceClientType(resource);
            lines.add("pub const " + clientType + " = struct {");
            lines.add("    client: *Client,");
            lines.add("");
            for (ResourceShape child : resources) {
                if (!resource.equals(parents.get(child.getId()))) {
                    continue;
                }
                String accessor = lowerFirst(SdkCodegen.resourceAccessorName(child));
                lines.add("    pub fn " + zigIdentifier(accessor) + "(self: " + clientType + ") "
                        + resourceClientType(child) + " {");
                lines.add("        return .{ .client = self.client };");
                lines.add("    }");
                lines.add("");
            }
            for (SdkCodegen.OperationBinding binding : byResource.get(resource.getId())) {
                renderClientMethod(lines, model, binding, clientType, "&self.client.runtime", 4);
            }
            lines.add("};");
            lines.add("");
        }
    }

    private static void renderClientMethod(
            List<String> lines,
            Model model,
            SdkCodegen.OperationBinding binding,
            String receiverType,
            String runtime,
            int indent
    ) {
        OperationShape operation = binding.operation();
        String spaces = " ".repeat(indent);
        String method = zigIdentifier(lowerFirst(binding.methodName()));
        String output = outputType(operation);
        String arguments = operation.getInput()
                .map(id -> ", input: " + zigIdentifier(id.getName()))
                .orElse("");
        String callArguments = operation.getInput().isPresent() ? ", input" : "";
        lines.add(spaces + "pub fn " + method + "(self: " + receiverType + arguments + ") !" + output + " {");
        lines.add(spaces + "    return execute" + operation.getId().getName() + "(" + runtime + callArguments + ");");
        lines.add(spaces + "}");
        lines.add("");
    }

    private static void renderBuilder(List<String> lines, Model model, OperationShape operation) {
        String inputType = operation.getInput().map(id -> zigIdentifier(id.getName())).orElse("void");
        String inputArg = operation.getInput().isPresent()
                ? (inputMembers(model, operation).isEmpty() ? "_: " : "input: ") + inputType
                : "_: void";
        lines.add("fn build" + operation.getId().getName()
                + "(allocator: Allocator, base_url: []const u8, " + inputArg + ") !core.Request {");
        lines.add("    var url = core.UrlBuilder.init(allocator);");
        lines.add("    errdefer url.deinit();");
        lines.add("    try url.base(base_url);");
        Map<String, MemberShape> membersByName = inputMembersByName(model, operation);
        for (PathPart part : pathParts(operation.expectTrait(HttpTrait.class).getUri().toString())) {
            if (part.kind() == PathPartKind.LITERAL) {
                lines.add("    try url.pathLiteral(" + zigString(part.value()) + ");");
            } else {
                MemberShape member = membersByName.get(part.value());
                if (member == null) throw new IllegalStateException("Missing input member for path label " + part.value());
                lines.add("    try url." + urlMethod(model, member.getTarget(), "path") + "("
                        + scalarValue(model, member.getTarget(), "input." + zigMemberIdentifier(member)) + ");");
            }
        }
        for (MemberShape member : inputMembers(model, operation)) {
            if (member.hasTrait(HttpQueryTrait.class)) {
                renderQuery(lines, model, member);
            }
        }
        HttpTrait http = operation.expectTrait(HttpTrait.class);
        lines.add("    return .{");
        lines.add("        .operation = " + zigString(operation.getId().getName()) + ",");
        lines.add("        .method = ." + http.getMethod() + ",");
        lines.add("        .url = try url.finish(),");
        lines.add("        .body = " + payloadExpression(model, operation) + ",");
        lines.add("        .expected_status = " + http.getCode() + ",");
        lines.add("    };");
        lines.add("}");
        lines.add("");
    }

    private static void renderExecutor(List<String> lines, OperationShape operation) {
        String inputArg = operation.getInput()
                .map(id -> ", input: " + zigIdentifier(id.getName()))
                .orElse("");
        String buildInput = operation.getInput().isPresent() ? "input" : "{}";
        lines.add("fn execute" + operation.getId().getName() + "(runtime: *core.ClientCore" + inputArg
                + ") !" + outputType(operation) + " {");
        lines.add("    const request = try build" + operation.getId().getName()
                + "(runtime.allocator, runtime.base_url, " + buildInput + ");");
        lines.add("    defer request.deinit(runtime.allocator);");
        lines.add("    const response = try runtime.sendRequest(request);");
        lines.add("    if (@intFromEnum(response.status) != request.expected_status) {");
        lines.add("        response.deinit(runtime.allocator);");
        lines.add("        return error.UnexpectedStatus;");
        lines.add("    }");
        if (operation.getOutput().isPresent()) {
            lines.add("    return core.decodeResponse(" + zigIdentifier(operation.getOutput().orElseThrow().getName())
                    + ", runtime.allocator, response);");
        } else {
            lines.add("    return response;");
        }
        lines.add("}");
        lines.add("");
    }

    private static void renderQuery(List<String> lines, Model model, MemberShape member) {
        Shape target = model.expectShape(member.getTarget());
        String field = "input." + zigMemberIdentifier(member);
        String queryName = zigString(member.expectTrait(HttpQueryTrait.class).getValue());
        if (target.isListShape()) {
            ShapeId item = target.asListShape().orElseThrow().getMember().getTarget();
            if (member.isRequired()) {
                lines.add("    for (" + field + ") |value| {");
            } else {
                lines.add("    if (" + field + ") |values| {");
                lines.add("        for (values) |value| {");
            }
            String indent = member.isRequired() ? "        " : "            ";
            lines.add(indent + "try url." + urlMethod(model, item, "query") + "(" + queryName + ", "
                    + scalarValue(model, item, "value") + ");");
            if (!member.isRequired()) lines.add("        }");
            lines.add("    }");
            return;
        }
        if (member.isRequired()) {
            lines.add("    try url." + urlMethod(model, member.getTarget(), "query") + "(" + queryName + ", "
                    + scalarValue(model, member.getTarget(), field) + ");");
        } else {
            lines.add("    if (" + field + ") |value| {");
            lines.add("        try url." + urlMethod(model, member.getTarget(), "query") + "(" + queryName + ", "
                    + scalarValue(model, member.getTarget(), "value") + ");");
            lines.add("    }");
        }
    }

    private static String payloadExpression(Model model, OperationShape operation) {
        for (MemberShape member : inputMembers(model, operation)) {
            if (!member.hasTrait(HttpPayloadTrait.class)) continue;
            String field = "input." + zigMemberIdentifier(member);
            String encode = rawPayload(model, member.getTarget())
                    ? "try allocator.dupe(u8, VALUE)"
                    : "try core.jsonEncode(allocator, VALUE)";
            if (member.isRequired()) {
                return encode.replace("VALUE", field);
            }
            return "if (" + field + ") |value| " + encode.replace("VALUE", "value") + " else null";
        }
        return "null";
    }

    private static boolean rawPayload(Model model, ShapeId target) {
        ShapeType type = resolvedScalarType(model, target);
        return type == ShapeType.BLOB || type == ShapeType.STRING;
    }

    private static String outputType(OperationShape operation) {
        return operation.getOutput()
                .map(id -> "core.TypedResponse(" + zigIdentifier(id.getName()) + ")")
                .orElse("core.Response");
    }

    private static List<MemberShape> inputMembers(Model model, OperationShape operation) {
        return operation.getInput()
                .map(id -> new ArrayList<>(model.expectShape(id).members()))
                .orElseGet(ArrayList::new);
    }

    private static Map<String, MemberShape> inputMembersByName(Model model, OperationShape operation) {
        Map<String, MemberShape> result = new LinkedHashMap<>();
        for (MemberShape member : inputMembers(model, operation)) {
            result.put(member.getMemberName(), member);
        }
        return result;
    }

    private static boolean isSimpleAlias(Shape shape) {
        return switch (shape.getType()) {
            case STRING, BYTE, SHORT, INTEGER, LONG, BIG_INTEGER, FLOAT, DOUBLE, BIG_DECIMAL,
                    BOOLEAN, BLOB, TIMESTAMP, DOCUMENT -> true;
            default -> false;
        };
    }

    private static String zigPreludeType(ShapeType type) {
        return switch (type) {
            case STRING, TIMESTAMP -> "[]const u8";
            case BYTE -> "i8";
            case SHORT -> "i16";
            case INTEGER -> "i32";
            case LONG -> "i64";
            case BIG_INTEGER -> "i128";
            case FLOAT -> "f32";
            case DOUBLE, BIG_DECIMAL -> "f64";
            case BOOLEAN -> "bool";
            case BLOB -> "[]const u8";
            case DOCUMENT -> "std.json.Value";
            default -> throw new IllegalArgumentException("Unsupported Zig prelude type " + type);
        };
    }

    private static String zigTargetType(Model model, ShapeId target) {
        if (target.getNamespace().equals("smithy.api")) {
            return zigPreludeType(model.expectShape(target).getType());
        }
        return zigIdentifier(target.getName());
    }

    private static ShapeType resolvedScalarType(Model model, ShapeId target) {
        Shape shape = model.expectShape(target);
        if (shape.isEnumShape()) return ShapeType.STRING;
        return shape.getType();
    }

    private static String urlMethod(Model model, ShapeId target, String prefix) {
        return prefix + switch (resolvedScalarType(model, target)) {
            case BYTE, SHORT, INTEGER, LONG, BIG_INTEGER -> "Int";
            case FLOAT, DOUBLE, BIG_DECIMAL -> "Float";
            case BOOLEAN -> "Bool";
            default -> "String";
        };
    }

    private static String scalarValue(Model model, ShapeId target, String expression) {
        return model.expectShape(target).isEnumShape() ? "@tagName(" + expression + ")" : expression;
    }

    private static String enumLiteral(MemberShape member) {
        return member.getTrait(EnumValueTrait.class)
                .flatMap(EnumValueTrait::getStringValue)
                .orElse(member.getMemberName());
    }

    private static String zigMemberIdentifier(MemberShape member) {
        String name = member.getTrait(JsonNameTrait.class).map(JsonNameTrait::getValue).orElse(member.getMemberName());
        return zigIdentifier(name);
    }

    private static String resourceClientType(ResourceShape resource) {
        return zigIdentifier(SdkCodegen.resourceAccessorName(resource)) + "ResourceClient";
    }

    private static String lowerFirst(String value) {
        if (value.isEmpty()) return value;
        return Character.toLowerCase(value.charAt(0)) + value.substring(1);
    }

    private static String zigIdentifier(String value) {
        if (value.matches("[A-Za-z_][A-Za-z0-9_]*") && !ZIG_KEYWORDS.contains(value)) {
            return value;
        }
        return "@\"" + escapeZig(value) + "\"";
    }

    private static List<PathPart> pathParts(String uri) {
        List<PathPart> parts = new ArrayList<>();
        int pos = 0;
        Matcher matcher = PATH_LABEL.matcher(uri);
        while (matcher.find()) {
            if (matcher.start() > pos) parts.add(new PathPart(PathPartKind.LITERAL, uri.substring(pos, matcher.start())));
            parts.add(new PathPart(PathPartKind.LABEL, matcher.group(1)));
            pos = matcher.end();
        }
        if (pos < uri.length()) parts.add(new PathPart(PathPartKind.LITERAL, uri.substring(pos)));
        return parts;
    }

    private static String zigString(String value) {
        return "\"" + escapeZig(value) + "\"";
    }

    private static String escapeZig(String value) {
        return value.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }

    private record PathPart(PathPartKind kind, String value) {}

    private enum PathPartKind { LITERAL, LABEL }
}
